b'Traceback (most recent call last):\n  File "/home/paolop/downward/builds/release/bin/translate/translate.py", line 747, in <module>\n    main()\n  File "/home/paolop/downward/builds/release/bin/translate/translate.py", line 718, in main\n    sas_task = pddl_to_sas(task)\n  File "/home/paolop/downward/builds/release/bin/translate/translate.py", line 547, in pddl_to_sas\n    reachable_action_params) = instantiate.explore(task)\n  File "/home/paolop/downward/builds/release/bin/translate/instantiate.py", line 116, in explore\n    prog = pddl_to_prolog.translate(task)\n  File "/home/paolop/downward/builds/release/bin/translate/pddl_to_prolog.py", line 167, in translate\n    translate_facts(prog, task)\n  File "/home/paolop/downward/builds/release/bin/translate/pddl_to_prolog.py", line 153, in translate_facts\n    translate_typed_object(prog, obj, type_dict)\n  File "/home/paolop/downward/builds/release/bin/translate/pddl_to_prolog.py", line 146, in translate_typed_object\n    supertypes = type_dict[obj.type_name].supertype_names\nKeyError: \'city\'\n'